### ISSUE TITLE
local.ERROR: Method Statamic\Auth\UserCollection::columns does not exist.

### ISSUE THREAD

**Issue by cemarta7** [jacksleight/statamic-memberbox#12]
## Bug Description
While trying to see the members it is giving the error.
I do have one member. The site lang is es. Not sure if that is creating the issue. I got the language translations working fine.
I check the Method Statamic\Auth\UserCollection::columns look at the second screenshot it is there as a private method. Maybe something change on a newer version of Statamic.

[2022-07-12 00:54:50] local.ERROR: Method Statamic\Auth\UserCollection::columns does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Statamic\\Auth\\UserCollection::columns does not exist. at /Users/camilomartinez/Sites/conecta/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]
#0 /Users/camilomartinez/Sites/conecta/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Support\\Collection->__call('columns', Array)
#1 /Users/camilomartinez/Sites/conecta/vendor/laravel/framework/src/Illuminate/Pagination/AbstractPaginator.php(785): Illuminate\\Pagination\\AbstractPaginator->forwardCallTo(Object(Statamic\\Auth\\UserCollection), 'columns', Array)
#2 /Users/camilomartinez/Sites/conecta/vendor/statamic/cms/src/Extensions/Pagination/LengthAwarePaginator.php(39): Illuminate\\Pagination\\AbstractPaginator->__call('columns', Array)
#3 /Users/camilomartinez/Sites/conecta/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Statamic\\Extensions\\Pagination\\LengthAwarePaginator->__call('columns', Array)
#4 /Users/camilomartinez/Sites/conecta/vendor/laravel/framework/src/Illuminate/Http/Resources/DelegatesToResource.php(155): Illuminate\\Http\\Resources\\Json\\JsonResource->forwardCallTo(Object(Statamic\\Extensions\\Pagination\\LengthAwarePaginator), 'columns', Array)
#5 /Users/camilomartinez/Sites/conecta/vendor/jacksleight/statamic-memberbox/src/Http/Controllers/CP/MembersController.php(80): Illuminate\\Http\\Resources\\Json\\JsonResource->__call('columns', Array)
#6 /Users/camilomartinez/Sites/conecta/vendor/jacksleight/statamic-memberbox/src/Http/Controllers/CP/MembersController.php(33): JackSleight\\StatamicMemberbox\\Http\\Controllers\\CP\\MembersController->json(Object(Statamic\\Http\\Requests\\FilteredRequest))
#7 /Users/camilomartinez/Sites/conecta/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): JackSleight\\StatamicMemberbox\\Http\\Controllers\\CP\\MembersController->index(Object(Statamic\\Http\\Requests\\FilteredRequest))

## How to Reproduce
Just click on the Members tab on the CP.

## Extra Detail
Error screen

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5060049/178523413-a588cac5-7429-4b2d-b94f-1d3d2ceabe97.png">

This is never reach
<img width="799" alt="image" src="https://user-images.githubusercontent.com/5060049/178526494-a9e82665-1ea6-4ebb-99c9-d02866f3c354.png">

## Environment

Statamic 3.3.18 Pro
Laravel 9.11.0
PHP 8.0.20
cnj/seotamic 2.0.6
jacksleight/statamic-memberbox 1.0.0

**Comment by cemarta7** [comment]
So the issue is that in Statamic 3.3 the method is private while on 3.2 it was public.
![image](https://user-images.githubusercontent.com/5060049/178556951-a9a5ccfb-d90c-49a9-92d5-649a62a74ee1.png)
